version: '3.8'

services:
  mongodb:
    image: mongo:4.2.0
    container_name: mongodb
    restart: always
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
      - MONGO_INITDB_DATABASE=$MONGODB_DATABASE
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - db:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - default
  backend:
    container_name: backend
    depends_on:
      - mongodb
    build:
      context: ./backend
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
      - /mnt:/mnt/
      - /usr/src/app/public/uploads
    restart: always
    env_file: ./.env
    expose:
      - $NODE_DOCKER_PORT
    stdin_open: true
    environment:
      DB_INSERTDATASAMPLES: true
      DB_HOST: mongodb
      DB_USER: $MONGODB_USER
      DB_PASSWORD: $MONGODB_PASSWORD
      DB_NAME: $MONGODB_DATABASE
      DB_PORT: $MONGODB_DOCKER_PORT
      CLIENT_ORIGIN: $CLIENT_ORIGIN
      API_SECRET: $API_SECRET
      JWT_EXPIRES_IN: $JWT_EXPIRES_IN
      FSHOSTADRESS: $FSHOSTADRESS
      FSHOST_FORDEV: $FSHOST_FORDEV
    networks:
      - default
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      args:
        - REACT_APP_BASE_URL=$REACT_APP_API_BASE_URL
    restart: unless-stopped
    networks:
      - default
    expose:
      - 8888
    stdin_open: true
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/share/nginx/html
  proxy:
    image: nginx:stable-alpine
    container_name: proxy
    restart: unless-stopped
    volumes:
      - /usr/share/nginx/html
      - "./nginx.conf:/etc/nginx/nginx.conf:delegated"
    ports:
      - "80:80"
    networks:
      - default

networks:
  default:


volumes:
  db:
